"""Wspólne moduły i narzędzia dla usług Regis."""

from shared.config import ConfigStore, get_service_root, sanitize_identifier
from shared.contracts import (
    AgentDefaultPromptDTO,
    CancelChatApiRequest,
    ChatMessageDTO,
    ChatResponseDTO,
    ChatSessionHistoryResponse,
    ChatSessionListResponse,
    ChatSessionSummaryDTO,
    CreateLLMProviderRequest,
    CreatePromptRequest,
    HealthResponse,
    LLMProviderDTO,
    LLMProviderListResponse,
    PromptDTO,
    PromptListResponse,
    ProviderMetadataResponse,
    ProviderOptionSpec,
    ProviderTypeSpecDTO,
    SelectLLMProviderRequest,
    SendChatMessageRequest,
    UpdatePromptRequest,
)
from shared.event_bus import Event, EventBus, EventHandler
from shared.logging import get_logger, setup_logging
from shared.voice_protocol import (
    CHANNELS,
    SAMPLE_RATE_HZ,
    SAMPLE_WIDTH_BYTES,
    SatelliteMessageType,
    ServerMessageType,
)

__version__ = "0.1.0"
__all__ = [
    "AgentDefaultPromptDTO",
    "CancelChatApiRequest",
    "CHANNELS",
    "ChatMessageDTO",
    "ChatResponseDTO",
    "ChatSessionHistoryResponse",
    "ChatSessionListResponse",
    "ChatSessionSummaryDTO",
    "ConfigStore",
    "CreateLLMProviderRequest",
    "CreatePromptRequest",
    "Event",
    "EventBus",
    "EventHandler",
    "HealthResponse",
    "LLMProviderDTO",
    "LLMProviderListResponse",
    "PromptDTO",
    "PromptListResponse",
    "ProviderMetadataResponse",
    "ProviderOptionSpec",
    "ProviderTypeSpecDTO",
    "SAMPLE_RATE_HZ",
    "SAMPLE_WIDTH_BYTES",
    "SatelliteMessageType",
    "SelectLLMProviderRequest",
    "SendChatMessageRequest",
    "ServerMessageType",
    "UpdatePromptRequest",
    "get_logger",
    "get_service_root",
    "sanitize_identifier",
    "setup_logging",
]
