"""Wspólne moduły i narzędzia dla usług Regis."""

from shared.config import ConfigStore, get_service_root, sanitize_identifier
from shared.contracts import (
    AgentDefaultPromptDTO,
    CancelChatApiRequest,
    ChatMessageDTO,
    ChatResponseDTO,
    ChatSessionHistoryResponse,
    ChatSessionListResponse,
    ChatSessionSummaryDTO,
    CreateLLMProviderRequest,
    CreatePromptRequest,
    DeletionResponse,
    HealthResponse,
    LLMFallbackChainResponse,
    LLMProviderDTO,
    LLMProviderListResponse,
    ModelSpecDTO,
    PromptDTO,
    PromptListResponse,
    ProviderMetadataResponse,
    ProviderModelsResponse,
    ProviderOptionChoice,
    ProviderOptionSpec,
    ProviderTypeSpecDTO,
    SelectLLMProviderRequest,
    SendChatMessageRequest,
    SetLLMFallbackChainRequest,
    UpdateLLMProviderRequest,
    UpdatePromptRequest,
)
from shared.discovery import DISCOVERY_MAGIC, DISCOVERY_UDP_PORT, decode_beacon, encode_beacon
from shared.event_bus import Event, EventBus, EventHandler
from shared.json_repository import ActiveInstancePointer, JsonInstanceRepository
from shared.logging import get_logger, setup_logging
from shared.voice_protocol import (
    CHANNELS,
    SAMPLE_RATE_HZ,
    SAMPLE_WIDTH_BYTES,
    SatelliteMessageType,
    ServerMessageType,
)

__version__ = "0.1.0"
__all__ = [
    "AgentDefaultPromptDTO",
    "CancelChatApiRequest",
    "CHANNELS",
    "ChatMessageDTO",
    "ChatResponseDTO",
    "ChatSessionHistoryResponse",
    "ChatSessionListResponse",
    "ChatSessionSummaryDTO",
    "ConfigStore",
    "CreateLLMProviderRequest",
    "CreatePromptRequest",
    "DeletionResponse",
    "DISCOVERY_MAGIC",
    "DISCOVERY_UDP_PORT",
    "decode_beacon",
    "encode_beacon",
    "Event",
    "EventBus",
    "EventHandler",
    "ActiveInstancePointer",
    "HealthResponse",
    "JsonInstanceRepository",
    "LLMFallbackChainResponse",
    "LLMProviderDTO",
    "LLMProviderListResponse",
    "PromptDTO",
    "PromptListResponse",
    "ModelSpecDTO",
    "ProviderMetadataResponse",
    "ProviderModelsResponse",
    "ProviderOptionChoice",
    "ProviderOptionSpec",
    "ProviderTypeSpecDTO",
    "UpdateLLMProviderRequest",
    "SAMPLE_RATE_HZ",
    "SAMPLE_WIDTH_BYTES",
    "SatelliteMessageType",
    "SelectLLMProviderRequest",
    "SendChatMessageRequest",
    "ServerMessageType",
    "SetLLMFallbackChainRequest",
    "UpdatePromptRequest",
    "get_logger",
    "get_service_root",
    "sanitize_identifier",
    "setup_logging",
]
