"""Wspólne moduły i narzędzia dla usług Regis."""

from shared.config import ConfigStore, get_service_root, sanitize_identifier
from shared.contracts import (
    CancelChatApiRequest,
    ChatMessageDTO,
    ChatResponseDTO,
    ChatSessionHistoryResponse,
    ChatSessionListResponse,
    ChatSessionSummaryDTO,
    CreateDeviceGroupRequest,
    CreateIntegrationRequest,
    CreateLLMProviderRequest,
    CreatePromptRequest,
    DeviceGroupDTO,
    DeviceGroupListResponse,
    HealthResponse,
    IntegrationDTO,
    IntegrationListResponse,
    LLMProviderDTO,
    LLMProviderListResponse,
    PromptDTO,
    PromptListResponse,
    ProviderMetadataResponse,
    ProviderOptionSpec,
    ProviderTypeSpecDTO,
    SelectLLMProviderRequest,
    SendChatMessageRequest,
    UpdateDeviceGroupRequest,
    UpdateIntegrationRequest,
    UpdatePromptRequest,
)
from shared.event_bus import Event, EventBus, EventHandler
from shared.logging import get_logger, setup_logging

__version__ = "0.1.0"
__all__ = [
    "CancelChatApiRequest",
    "ChatMessageDTO",
    "ChatResponseDTO",
    "ChatSessionHistoryResponse",
    "ChatSessionListResponse",
    "ChatSessionSummaryDTO",
    "ConfigStore",
    "CreateDeviceGroupRequest",
    "CreateIntegrationRequest",
    "CreateLLMProviderRequest",
    "CreatePromptRequest",
    "DeviceGroupDTO",
    "DeviceGroupListResponse",
    "Event",
    "EventBus",
    "EventHandler",
    "HealthResponse",
    "IntegrationDTO",
    "IntegrationListResponse",
    "LLMProviderDTO",
    "LLMProviderListResponse",
    "PromptDTO",
    "PromptListResponse",
    "ProviderMetadataResponse",
    "ProviderOptionSpec",
    "ProviderTypeSpecDTO",
    "SelectLLMProviderRequest",
    "SendChatMessageRequest",
    "UpdateDeviceGroupRequest",
    "UpdateIntegrationRequest",
    "UpdatePromptRequest",
    "get_logger",
    "get_service_root",
    "sanitize_identifier",
    "setup_logging",
]
